version: '3.2'
services:
  scala-text-pdf-compile:
    image: ghcr.io/scala-text/scala-text-pdf:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      cache_from:
        - ghcr.io/scala-text/scala-text-pdf:latest
    volumes:
      - .:/workdir
      - ~/.sbt:/root/.sbt
      - ~/.ivy2:/root/.ivy2
